<footer id="site-footer" class="site-footer">
  <div class="container">
    <div class="logo"><a href="#"><img src="theme/images/logo.png" alt=""/></a></div>
    <div class="info">
      <p>
        <span class="item-info"><strong>PHONE</strong> <a href="tel:8004778909">800.477.8909</a></span>
        <span class="item-info"><strong>FAX</strong> 405.755.5283</span>
        <span class="item-info"><a href="mailto:info@phyconbill.com">info@phyconbill.com</a></span>
      </p>
      <p>4401 W Memorial Rd Ste 121  Oklahoma City, OK 73134</p>
    </div>
    <div class="navigation">
      <ul class="menu">
        <li class="active"><a href="#">SERVICES</a></li>
        <li><a href="#">about</a></li>
        <li><a href="#">patients</a></li>
        <li><a href="#">contact us</a></li>
        <li><a href="#">news</a></li>
      </ul>
    </div>
  </div>
</footer>
<div class="b-modal modal fade" id="sign-up-for-demo" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <div class="modal-body">
        <h5>Sign Up for a Demo</h5>
        <p>Our dashboard software solutions put you in control of all aspects of your group’s operations, billing, finances and more.</p>
        <div class="form form-sign-up-for-demo">
          <div class="form-item">
            <input class="form-text" type="text" placeholder="First Name"/>
          </div>
          <div class="form-item">
            <input class="form-text" type="text" placeholder="phone"/>
          </div>
          <div class="form-item">
            <input class="form-text" type="text" placeholder="last Name"/>
          </div>
          <div class="form-item">
            <input class="form-text" type="text" placeholder="e-mail"/>
          </div>
          <div class="form-actions"><input class="form-submit" type="submit" value="submit"/></div>
        </div>
      </div>
    </div>
  </div>
</div>