<header id="site-header" class="site-header">
  <div class="container">
    <div class="logo"><a href="#"><img src="theme/images/logo.png" alt=""/></a></div>
    <div class="navigation">
      <div class="content">
        <ul class="menu">
          <li><a href="#">pay bill</a></li>
          <li><a href="#">dashboard</a></li>
        </ul>
      </div>
    </div>
    <nav class="nav">
      <a class="btn-nav" href="#"></a>

      <div class="block-menu-block">
        <ul class="menu">
          <li class="expanded">
            <a href="#">services</a>
            <ul class="menu">
              <li class="expanded">
                <a href="#">Finance</a>
                <ul class="menu">
                  <li><a href="#">ER Billing</a></li>
                  <li><a href="#">productivity</a></li>
                </ul>
              </li>
              <li><a href="#">Risk Management</a></li>
              <li><a href="#">Performance management</a></li>
              <li><a href="#">Practice management</a></li>
              <li><a href="#">coding & compliance</a></li>
              <li><a href="#">Billing Review</a></li>
              <li><a href="#">Physician Evaluation</a></li>
            </ul>
          </li>
          <li class="expanded active">
            <a href="#">ABOUT</a>
            <ul class="menu">
              <li><a href="#">services</a></li>
              <li class="expanded">
                <a href="#">our company</a>
                <ul class="menu">
                  <li><a href="#">History & Mission</a></li>
                  <li><a href="#">Clients</a></li>
                </ul>
              </li>
              <li><a href="#">careers</a></li>
              <li><a href="#">news</a></li>
              <li><a href="#">Contact us</a></li>
              <li><a href="#">request a demo</a></li>
            </ul>
          </li>
          <li class="expanded">
            <a href="#">patients</a>
            <ul class="menu">
              <li><a href="#">Pay Your Bill</a></li>
              <li><a href="#">Questions</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>

    <a href="#" class="btn-search"></a>
    <div class="form form-search">
      <div class="form-type-text">
        <input type="text" class="form-text"/>
      </div>
      <div class="btn-wrap">
        <input type="submit" class="form-submit"/>
      </div>
    </div>
  </div>
</header>